package cn.ninth.novel.domain.chapter.service.session;

/**
 * 章节生成会话对外发送的 SSE 事件类型。
 */
public enum ChapterGenerationEventType {
    GENERATION_STARTED,
    DRAFT_STARTED,
    DRAFT_CHUNK,
    DRAFT_COMPLETED,
    REVIEW_STARTED,
    REVIEW_COMPLETED,
    REVISION_STARTED,
    REVISION_COMPLETED,
    REVIEW_FAILED,
    HUMAN_REVIEW_REQUIRED,
    COMPRESSION_STARTED,
    COMPRESSION_COMPLETED,
    PERSIST_STARTED,
    PERSIST_COMPLETED,
    GENERATION_COMPLETED,
    GENERATION_ABORTED,
    GENERATION_FAILED,
    GENERATION_CANCELLED
}
